/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bankaccount;
import java.util.*;
// import java.io.File;
// import java.util.Formatter;
import java.util.Scanner;

public class Main {
  public static String textMessage = "";
  public static String[] bankOptions = {
    "Access bank account",
    "Create bank account",
    "Exit",
  };
  public static void userScreenInput() {
    Scanner sc = new Scanner(System.in);
    CreateAccount accountObj = new CreateAccount();
   
    System.out.println("Please select an option below");
    for (int i = 0; i < bankOptions.length; i++) {
      System.out.println(i + 1 + ". " + bankOptions[i]);
    }
    int option = sc.nextInt();
    while (option != 1 && option != 2 && option != 3) {
      System.out.println("Please select a valid option.");
      option = sc.nextInt();
    }
    switch (option) {
      case 1:
        AccessAccount myObj = new AccessAccount();
        System.out.println("Please enter your Id Number");
        sc.nextLine();
        String IdNumber = sc.nextLine();
        myObj.getAccountDetails(IdNumber);
        break;
      case 2:
        System.out.println(
          "You will be asked to enter required information, name, surname, id, email etc.."
        );
        accountObj.getIdEmailAndName();
        break;
      case 3:
        System.out.println("Have a nice day!");
        sc.close();
        break;
      default:
        break;
    }
    sc.close();
  }

  public static void main(String[] args) {
   
  }


  // public static void main(String[] args) {
  //   Scanner scan = new Scanner(System.in);
  //   String s = scan.next();
  //   int k = scan.nextInt();
  //   scan.close();

  //   System.out.println(getSmallestAndLargest(s, k));
  // }
}
